#!/usr/bin/env bash

port="${2:-2}"

case $1 in
    -) xrandr --output DP1-$port --off ;;
    +) xrandr --output DP1-$port --auto --same-as  eDP1 ;;
    *) xrandr --output DP1-$port --auto --right-of eDP1 ;;
esac
